### ISSUE TITLE
function retracing in tensorflow 2.3 with forward nufft

### ISSUE THREAD

**Issue by zacman2400** [zaccharieramzi/tfkbnufft#23]
First, thank you so much for this implementation. I have been getting the following warning with the forward nufft in tf 2.3:

```
WARNING:tensorflow:11 out of the last 11 calls to <tensorflow.python.ops.custom_gradient.Bind object at 0x7fb3044ab450> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
```

Have you been getting this warning when you run this? I am happy to try and debug it myself, but I need to figure out where in the code the function call is happening.

**Comment by zaccharieramzi** [comment]
Hi @zacman2400 ,

Sorry for getting back to you so late, for some reason my watch setting was not on by default.
By any chance could you give me a link to a google colab where I can reproduce this error?
Also don't forget to post the entire stack trace, as well as use code formatting for your next issues to allow for further understanding.

However, I have been getting this error for some other reasons in other contexts.
See for example [this](https://github.com/tensorflow/tensorflow/issues/38561) and the linked issues.

It seems that up until recently, some people were dealing with this issue ([see](https://github.com/tensorflow/tensorflow/issues/38561#issuecomment-673811919)).

I don't have a test for the integration of the NUFFT in a Keras model unfortunately so it wouldn't show up in the CI logs.

**Comment by zaccharieramzi** [comment]
For future reference, with TensorFlow version 2.3, a reproducible example is the following (based on the basic example notebook):

```python
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from skimage.data import shepp_logan_phantom
from tfkbnufft import kbnufft_forward, kbnufft_adjoint
from tfkbnufft.kbnufft import KbNufftModule
from tfkbnufft.mri.dcomp_calc import calculate_radial_dcomp_tf

dtype = tf.float32

image = shepp_logan_phantom().astype(np.complex)
im_size = image.shape
image = tf.convert_to_tensor(image)[None, None, ...]
nufft_ob = KbNufftModule(im_size=im_size, grid_size=grid_size, norm='ortho')

def create_traj(nspokes=40):
    spokelength = image.shape[-1] * 2
    grid_size = (spokelength, spokelength)

    ga = np.deg2rad(180 / ((1 + np.sqrt(5)) / 2))
    kx = np.zeros(shape=(spokelength, nspokes))
    ky = np.zeros(shape=(spokelength, nspokes))
    ky[:, 0] = np.linspace(-np.pi, np.pi, spokelength)
    for i in range(1, nspokes):
        kx[:, i] = np.cos(ga) * kx[:, i - 1] - np.sin(ga) * ky[:, i - 1]
        ky[:, i] = np.sin(ga) * kx[:, i - 1] + np.cos(ga) * ky[:, i - 1]

    ky = np.transpose(ky)
    kx = np.transpose(kx)

    ktraj = np.stack((ky.flatten(), kx.flatten()), axis=0)
    ktraj = tf.convert_to_tensor(ktraj)[None, ...]
    return ktraj

for nspokes in range(10, 200, 10):
    ktraj = create_traj(nspokes)
    kdata = kbnufft_forward(nufft_ob._extract_nufft_interpob())(image, ktraj)
```

**Comment by zaccharieramzi** [comment]
The fix for this example is pretty simple actually:
```python
forw = kbnufft_forward(nufft_ob._extract_nufft_interpob())
for nspokes in range(10, 200, 10):
    ktraj = create_traj(nspokes)
    kdata = forw(image, ktraj)
```

You need to define the forward operation for a given interpolation object once, otherwise it defines a `tf.function` in a loop which triggers the warning.

I am going to consider this issue closed, but @zacman2400 if this was not your context, please feel free to re-open.
