### ISSUE TITLE
Basic KB-NUFFT Example_Error

### ISSUE THREAD

**Issue by TRDim** [zaccharieramzi/tfkbnufft#34]
Hello, thank you so much for your code. 
I have an issue when I try to run the example in the Notebook. 
Even if it seems to run well from the printed execution output when I try to run it on my own, 
I face the following error:

![image](https://user-images.githubusercontent.com/38346838/112869161-bc253480-90b4-11eb-88c1-8d37c1eb65ba.png)

Thank you.

**Comment by zaccharieramzi** [comment]
Hello @TRDim ,

Thanks for using the code and contributing by reporting this error.
The notebook was not tested before merging #30 , and it turns out that a very small bug got introduced.

Let me fix it real quick so that you can use the nufft asap.

**Comment by chaithyagr** [comment]
Ahh, dang. Maybe add the notebook run to github workflow in some form to prevent this?

**Comment by TRDim** [comment]
Thank you for your immediate response :)
