### ISSUE TITLE
[URGENT] Test fails but CI reports a pass

### ISSUE THREAD

**Issue by chaithyagr** [zaccharieramzi/tfkbnufft#39]
CI reports a pass while the pytest actually reported a fail. This could miss some crucial issues.
An example for this is :

https://github.com/zaccharieramzi/tfkbnufft/pull/38/checks?sha=4b18de94d6b40e14ce1f7e14e3e80e5c5da7052b

We may need to move to setting up a test CI which is stronger.

**Comment by zaccharieramzi** [comment]
The example is gone now, do you have a screenshot by any chance? or do you remember which run exactly it was?

**Comment by chaithyagr** [comment]
Oh nope, no screenshot. Let me see, I think it should still esxist. Will post screenshot. The test was dcomp test

**Comment by chaithyagr** [comment]
It seems to still be there... 

![image](https://user-images.githubusercontent.com/8596659/115689993-e63ce000-a35c-11eb-96a3-3ec38e7bd414.png)

![image](https://user-images.githubusercontent.com/8596659/115690061-f6ed5600-a35c-11eb-9f7a-fd4e0efdfb69.png)

**Comment by zaccharieramzi** [comment]
I see this is because we run both in the same sh file, and it outputs the last info

I think we should have a `set -x` or something like that. Let me see.
